// Generates src/landing-glyphs.js: real TypeFab outlines and automatic bridges
// for the landing page's Before / After section. Run: node scripts/landing-glyphs.mjs
import fs from "node:fs";
import opentype from "opentype.js";
import {
  automaticBridges,
  cutGeometry,
  pathData,
  worldContours,
  bounds,
  transform,
} from "../src/geometry.js";
import { layoutGlyphs } from "../src/typography.js";

const fonts = {
  zen: opentype.parse(
    fs.readFileSync("public/fonts/ZenKakuGothicNew-Regular.ttf").buffer,
  ),
  shippori: opentype.parse(
    fs.readFileSync("public/fonts/ShipporiMincho-Regular.ttf").buffer,
  ),
};
const samples = [
  ["A", "zen"],
  ["O", "zen"],
  ["R", "zen"],
  ["8", "zen"],
  ["日", "shippori"],
  ["あ", "zen"],
];
const num = (n) => Number(n.toFixed(3));
const glyphs = samples.map(([char, font]) => {
  const item = {
    id: `g-${char}`,
    type: "text",
    text: char,
    font,
    size: 40,
    spacing: 0,
    x: 0,
    y: 0,
    rotation: 0,
    vertical: false,
  };
  item.contours = layoutGlyphs(item, fonts[font]).flatMap((g) => g.contours);
  const bridges = automaticBridges([item]);
  const cut = cutGeometry([item, ...bridges]);
  if (cut.untouched)
    throw Error(`${char}: ${cut.untouched} contour(s) left without a bridge`);
  const box = bounds(worldContours(item));
  const pad = 3;
  return {
    char,
    font,
    viewBox: [box.x - pad, box.y - pad, box.w + pad * 2, box.h + pad * 2]
      .map(num)
      .join(" "),
    outline: pathData(worldContours(item)),
    bridges: bridges.map((b) =>
      [
        [-1, -1],
        [1, -1],
        [1, 1],
        [-1, 1],
      ]
        .map(([x, y]) => transform({ x: (x * b.w) / 2, y: (y * b.h) / 2 }, b))
        .map((p) => `${num(p.x)},${num(p.y)}`)
        .join(" "),
    ),
    cut: pathData(cut.paths),
    holes: bridges.length,
  };
});
fs.writeFileSync(
  "src/landing-glyphs.js",
  `// Generated by scripts/landing-glyphs.mjs from the bundled fonts with\n// src/geometry.js (automatic bridges, 1.5 mm). Do not edit by hand.\nexport const GLYPHS = ${JSON.stringify(glyphs)};\n`,
);
console.log(
  glyphs.map((g) => `${g.char} (${g.font}): ${g.holes} bridge(s)`).join("\n"),
);
